config/routes.rb
Rails.application.routes.draw do
  
  root "loans#index"
  resources :adjustments
  devise_for :users
  resources :loans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_cdn_assets.html.erb
<meta charset="utf-8">

<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css">
<link rel="stylesheet" href="https://bootswatch.com/4/minty/bootstrap.min.css">

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js"></script>

<script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/js/all.min.js"></script>

app/views/shared/_flashes.html.erb
<div class="row">
  <div class="col-md-12">
    <% if notice.present? %>
      <div class="alert alert-success alert-dismissable" role="alert">
        <%= notice %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <% if alert.present? %>
      <div class="alert alert-warning alert-dismissable" role="alert">
        <%= alert %>

        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary mb-4">
  <div class="container">
    <%= link_to 'Loan Planner', root_path, class: "navbar-brand" %>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsible-nav-links" aria-controls="collapsible-nav-links" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="collapsible-nav-links">
      <ul class="navbar-nav mr-auto">
        <!--<li class="nav-item dropdown">-->
          <!--<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">-->
          <!--  Resources-->
          <!--</a>-->
          <!--<div class="dropdown-menu" aria-labelledby="navbarDropdown">-->
          <li class="nav-item">           
            <%= link_to 'Loans', loans_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Adjustments', adjustments_path, class: "nav-link" %>
          </li>
          </div>
        <!--</li>-->
      </ul>
      <ul class="navbar-nav">
        <% if current_user.blank? %>
          <li class="nav-item">
            <%= link_to 'Sign in', user_session_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'Edit profile', edit_user_registration_path, class: "nav-link" %>
          </li>

          <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div> <!-- .navbar-collapse -->
  </div> <!-- .container -->
</nav>