config/routes.rb
Rails.application.routes.draw do
  
  root "loans#index"
  resources :adjustments
  devise_for :users
  resources :loans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/loan.rb
# == Schema Information
#
# Table name: loans
#
#  id                  :bigint           not null, primary key
#  current_balance     :float
#  original_amount     :float
#  interest_rate       :float
#  periods_in_year     :integer
#  user_id             :integer
#  loan_name           :string
#  monthly_min_payment :float
#  schedule_hash       :jsonb
#  adj_schedule_hash   :jsonb
#  created_at          :datetime         not null
#  updated_at          :datetime         not null
#
class Loan < ApplicationRecord
  has_many :adjustments, :dependent => :destroy
  belongs_to :user
    
    validates :interest_rate, :numericality => { :greater_than => 0 }
    validates :interest_rate, :presence => true
    validates :current_balance, :numericality => { :greater_than_or_equal_to => 0 }
    validates :current_balance, :presence => true
    validates :original_amount, :numericality => { :greater_than => 0 }
    validates :monthly_min_payment, :presence => true
    validates :monthly_min_payment, :numericality => { :greater_than => 0 }
    validates :periods_in_year, :presence => true
    validates :periods_in_year, :numericality => { :greater_than => 0 }
    
    def pay_schedule
        i=0
        end_balance = current_balance
        pmt_amt = monthly_min_payment
        int_rate =  interest_rate / 100
        periods = periods_in_year
        mo_int = int_rate/periods
        cum_int = 0
        
        @pmt_schedule = []
        
        # Loan without any additional payments
        while end_balance > 0
          beg_balance = end_balance
          pmt_no = i+1
          interest = beg_balance*mo_int
          
          # Checks if the scheduled payment exceeds the ammount that is still owed on the loan
          # Adjusts payment down to the beginng balance + interest accrued if it us
           
          if beg_balance + interest < pmt_amt
            pmt_amt = beg_balance + interest
          end
          
          principal = pmt_amt - interest
          end_balance = beg_balance - principal
          cum_int += interest
          loan_name = self.loan_name
          
          
          @pmt_schedule[i] = {"pmt_no" => pmt_no , "beg_balance" => beg_balance.round(2), "pmt_amt" => pmt_amt , "principal" => principal , "interest" => interest , "end_balance" => end_balance, "cum_int" =>cum_int, "loan_name" => loan_name}
          i += 1
        end
        
        return @pmt_schedule
    end


    def adj_pay_schedule( pmt_adj_table )
        j=0
        end_balance_adj = current_balance
        pmt_amt = monthly_min_payment
        int_rate =  interest_rate / 100
        periods = periods_in_year
        mo_int = int_rate/periods
        cum_int_adj = 0
        
        @pmt_schedule_adj = []
        
        while end_balance_adj > 0
          beg_balance_adj = end_balance_adj
          pmt_amt = self.monthly_min_payment
          pmt_no = j+1
          interest = beg_balance_adj*mo_int
          
          pmt_amt_adj = pmt_amt
          
          # Checks to see if there are any payment adjustments happpening
          # during this loan period and adjusting payment accordingly
          
          pmt_adj_table.each do | adjustment |
            if adjustment.payment_occurrence == "One Time" && adjustment.beg_pay_adj == pmt_no
              pmt_amt_adj += adjustment.pmt_adjustment
            elsif adjustment.payment_occurrence == "Recurring" && adjustment.beg_pay_adj <= pmt_no
              pmt_amt_adj += adjustment.pmt_adjustment
            elsif adjustment.payment_occurrence == "Between" && adjustment.beg_pay_adj <= pmt_no && adjustment.end_pay_adj >= pmt_no
              pmt_amt_adj += adjustment.pmt_adjustment
            else
              pmt_amt_adj = pmt_amt_adj
            end
          end
          
          # Checks if the scheduled payment exceeds the ammount that is still owed on the loan
          # Adjusts payment down to the beginng balance + interest accrued if it us
           
          if beg_balance_adj + interest < pmt_amt_adj
            pmt_amt_adj = beg_balance_adj + interest
          end
          
          principal = pmt_amt_adj - interest
          end_balance_adj = beg_balance_adj - principal
          cum_int_adj += interest
          loan_name = self.loan_name
          
          
          @pmt_schedule_adj[j] = {"pmt_no" => pmt_no , "beg_balance_adj" => beg_balance_adj.round(2), "pmt_amt_adj" => pmt_amt_adj , "principal" => principal , "interest" => interest , "end_balance_adj" => end_balance_adj, "cum_int_adj" =>cum_int_adj, "loan_name" => loan_name}
          j += 1
        end    
        
        
        
        return @pmt_schedule_adj
    end

    def monthly_min_payment_for_payback_period( payback_period )
      rate = interest_rate/100/periods_in_year
      periods = payback_period * periods_in_year

      calculated_monthly_min_payment = original_amount * ( rate*(1 + rate)**periods) / ((1+rate)**periods -1)
    end

    def Loan.index_page_charts
      # Initialize Variable
      @pmt_schedule_chart = []
      @adj_pmt_schedule_chart = []
      @total_interest = 0
      @total_adj_interest = 0
      @pay_off_period = []
      @pay_off_period_adj = []
      
      @loans = Loan.all.to_ary   
       
        
      @loans.each_with_index do |loan , index|
        pmt_schedule = loan.pay_schedule;  
        pmt_schedule_adj = loan.adj_pay_schedule(loan.adjustments);
        @pmt_schedule_chart[index] =  pmt_schedule.map{|t| [ t["pmt_no"], t["beg_balance"] ] };
        @adj_pmt_schedule_chart[index] = pmt_schedule_adj.map{|t| [ t["pmt_no"], t["beg_balance_adj"] ] };
        @total_interest += pmt_schedule[-1].fetch("cum_int");
        @total_adj_interest += pmt_schedule_adj[-1].fetch("cum_int_adj");
        @pay_off_period[index] = pmt_schedule.length;
        @pay_off_period_adj[index] = pmt_schedule_adj.length;
      end
      
  
  
      # Summarize the data for the compare charts
      total_balance = [];
      total_periods = [];
      @total_pmt_schedule_chart = [];
      
      @pmt_schedule_chart.each do |pmt|
        pmt.each_with_index do |period , index|
          if total_balance[index] == nil
              total_balance[index] = 0;
              total_balance[index] += period[1]
          else
              total_balance[index] += period[1]
          end
          
          total_periods[index] = period[0]
          @total_pmt_schedule_chart[index] = [total_periods[index] ,total_balance[index].round(2) ]
        end
      end
      
      total_adj_balance = [];
      total_adj_periods = [];
      @total_adj_pmt_schedule_chart = [];
      
      @adj_pmt_schedule_chart.each do |pmt|
        pmt.each_with_index do |period , index|
          if total_adj_balance[index] == nil
              total_adj_balance[index] = 0;
              total_adj_balance[index] += period[1]
          else
              total_adj_balance[index] += period[1]
          end
          
          total_adj_periods[index] = period[0]
          @total_adj_pmt_schedule_chart[index] = [total_adj_periods[index] ,total_adj_balance[index].round(2) ]
        end
      end

      return @pmt_schedule_chart, @adj_pmt_schedule_chart, @total_interest, @total_adj_interest, @pay_off_period, @pay_off_period_adj
    end

end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  before_action :set_loan, only: %i[ show edit update destroy ]
  after_action :verify_policy_scoped, only: [:index]
  after_action :verify_authorized, except: [:index]


   def index
      #Replaced with Pundit Scope
      #@loans = current_user.loans
      @loans = policy_scope(Loan)

      @loans.index_page_charts

    render
  end

  def show
    #Pundit 
    authorize @loan


    @pmt_schedule = @loan.pay_schedule;
    @pmt_schedule_adj = @loan.adj_pay_schedule(@loan.adjustments)
    
    @pmt_schedule_chart =  @pmt_schedule.map{|t| [ t["pmt_no"], t["beg_balance"] ] };
    @adj_pmt_schedule_chart = @pmt_schedule_adj.map{|t| [ t["pmt_no"], t["beg_balance_adj"] ] };

    render
  end

  def new
    @loan = Loan.new
    authorize @loan
  end

  def create 
    @loan = Loan.new(loan_params)
    authorize @loan

    respond_to do |format|
      if @loan.save
        format.html { redirect_to @loan, notice: "Loan was successfully created." }
        format.json { render :show, status: :created, location: @loan }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    authorize @loan
    render
  end

  def update
    authorize @loan
    respond_to do |format|
      if @loan.update(loan_params)
        format.html { redirect_to @loan, notice: "Loan was successfully updated." }
        format.json { render :show, status: :ok, location: @loan }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @loan.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    authorize @loan
    @loan.destroy

    respond_to do |format|
      format.html { redirect_to loans_url, notice: "Loan was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_loan
      @loan = Loan.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def loan_params
      params.require(:loan).permit(:current_balance, :original_amount, :interest_rate, :periods_in_year, :user_id, :loan_name, :monthly_min_payment, :schedule_hash, :adj_schedule_hash)
    end
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/views/loans/_form.html.erb
<%= form_with(model: loan) do |form| %>
  <% if loan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(loan.errors.count, "error") %> prohibited this loan from being saved:</h2>

      <ul>
        <% loan.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<hr>
  <div class="form-group">
    <%= form.label :current_balance %>
    <%= form.text_field :current_balance, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :original_amount %>
    <%= form.text_field :original_amount, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :interest_rate %>
    <%= form.text_field :interest_rate, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :periods_in_year %>
    <%= form.number_field :periods_in_year, class: "form-control" %>
  </div>

  <%= form.hidden_field :user_id, value: current_user.id%>

  <div class="form-group">
    <%= form.label :loan_name %>
    <%= form.text_field :loan_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :monthly_min_payment %>
    <%= form.text_field :monthly_min_payment, class: "form-control" %>
  </div>

  <div class="btn btn-block btn-outline-primary">
    <%= form.submit %>
  </div>

<% end %>
 
<hr>

app/views/loans/_index_row.html.erb
<tr>
  <td><%= loan.loan_name %></td>
  <td><%= number_to_currency(loan.current_balance) %></td>     
  <td><%= number_to_currency(loan.original_amount) %></td>
  <td><%= number_to_percentage(loan.interest_rate) %></td>
  <td><%= number_to_currency(loan.monthly_min_payment) %></td>
  <td><%= @pay_off_period[index] %></td>
  <td><%= @pay_off_period_adj[index] %></td>
  <td><%= link_to "Show details", loan %></td>
</tr>

app/views/loans/_schedule_details.html.erb
    <table class="table">
      <tr>

        <th>
          Payment No.
        </th>

        <th>
          Beginning Balance
        </th>

        <th>
          Scheduled Payment
        </th>

        <th>
          Adjusted Payment
        </th>

        <th>
          Interest
        </th>

        <th>
          Ending Balance
        </th>

        <th>
          Cumulative Interest
        </th>

        <th>
          Adj End Balance
        </th>

        <th>
          Adj Cumulative Interest
        </th>
      </tr>

     <% pmt_schedule.each do |schedule| %>
      <tr>

        <td>
          <%= schedule["pmt_no"] %>
        </td>

        <td>
          <%= number_to_currency(schedule["beg_balance"]) %>
        </td>

        <td>
          <%= number_to_currency(schedule["pmt_amt"]) %>
        </td>

        <td>
          <% if pmt_schedule_adj[schedule["pmt_no"] - 1].blank? %>
            <%= number_to_currency(0) %>
          <% else %>
            <%= number_to_currency(pmt_schedule_adj[schedule["pmt_no"] - 1]["pmt_amt_adj"]) %>
          <% end %>
        </td>

        <td>
          <%= number_to_currency(schedule["interest"]) %>
        </td>

        <td>
          <%= number_to_currency(schedule["end_balance"]) %>
        </td>
        <td>
          <%= number_to_currency(schedule["cum_int"]) %>
        </td>

        <td>
          <% if pmt_schedule_adj[schedule["pmt_no"] - 1].blank? %>
            <%= number_to_currency(pmt_schedule_adj[pmt_schedule_adj.length-1]["end_balance_adj"]) %>
          <% else %>
            <%= number_to_currency(pmt_schedule_adj[schedule["pmt_no"] - 1]["end_balance_adj"]) %>
          <% end %>
        </td>

        <td>
          <% if pmt_schedule_adj[schedule["pmt_no"] - 1].blank? %>
            <%= number_to_currency(pmt_schedule_adj[pmt_schedule_adj.length-1]["cum_int_adj"]) %>
          <% else %>
            <%= number_to_currency(pmt_schedule_adj[schedule["pmt_no"] - 1]["cum_int_adj"]) %>
          <% end %>
        </td>
        
      </tr>
    <% end %>
    
    </table>

app/views/loans/edit.html.erb
<h1>Editing Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Show', @loan %> |
<%= link_to 'Back', loans_path %>

app/views/loans/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      All loans
    </h1>
    <%= link_to "Add a new loan", new_loan_path, class: "btn btn-block btn-outline-secondary" %>
  </div>
</div>


<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table table-hover">
      <tr>
        <th> Loan Name </th>
        <th> Current Balance </th>
        <th> Original Amount </th>
        <th> Interest Rate </th>
        <th> Monthly Minimum </th>
        <th> Original Payoff Period </th>
        <th> Adjusted Payoff Period </th>        
        <th> </th>
      </tr>

      <% @loans.each_with_index do |loan , index| %>
        <%= render "loans/index_row", loan: loan, index: index %>
      <% end %>
    </table>
  </div>
</div>


<div>
  <%= column_chart [{name: "Total Balance" , data: @total_pmt_schedule_chart} , {name: "Total Balance with Adjustments" , data: @total_adj_pmt_schedule_chart}], prefix: "$" , thousands: "," %>
</div> 

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table">
      <tr>

        <th> Total Interest with Minimum Payments </th>
        <th> Original Time Until Payoff </th>
        <th> Total Interest with Adjusted Payments </th>
        <th> Adjusted Time Until Payoff </th>
        <th> Total Savings! </th>               
        <th> Total Time Savings! </th>
      </tr>
      <tr>
        <td> <%= number_to_currency(@total_interest) %> </td>
        <td> <%= @pay_off_period.max %> </td>
        <td> <%= number_to_currency(@total_adj_interest) %> </td>
        <td> <%= @pay_off_period_adj.max %> </td>
        <td> <%= number_to_currency(@total_interest - @total_adj_interest ) %> </td>
        <td> 
          <% if @pay_off_period_adj.max == nil || @pay_off_period.max == nil%>
            0 Months
          <% else %>
            <%= @pay_off_period.max - @pay_off_period_adj.max %> Months
          <% end %>
        </td>
      </tr>
    </table>
  </div>
</div>        

app/views/loans/new.html.erb
<h1>New Loan</h1>

<%= render 'form', loan: @loan %>

<%= link_to 'Back', loans_path %>

app/views/loans/show.html.erb
<div class="row mb-3">
  <div class="col-md-8 offset-md-2">
    <h1>
      <%= @loan.loan_name %> Details
    </h1>

    <div class="row mb-3">
      <div class="col">
        <%= link_to "Go back", loans_path, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to "Edit loan", edit_loan_path, class: "btn btn-block btn-outline-secondary" %>
      </div>

       <div class="col">
        <%= link_to 'Delete', @loan, method: :delete, class: "btn btn-block btn-outline-secondary" %>
      </div> 

    </div> 

    <dl>
      <dt>
        Loan name
      </dt>
      <dd>
        <%= @loan.loan_name %>
      </dd>
      
      <dt>
        Current balance
      </dt>
      <dd>
        <%= number_to_currency(@loan.current_balance) %>
      </dd>

      <dt>
        Original amount
      </dt>
      <dd>
        <%= number_to_currency(@loan.original_amount) %>
      </dd>

      <dt>
        Interest rate
      </dt>
      <dd>
        <%= number_to_percentage(@loan.interest_rate) %>
      </dd>
      
      <dt>
        Minimum Payment
      </dt>
      <dd>
        <%= number_to_currency(@loan.monthly_min_payment) %>
      </dd>

      <dt>
        Periods in year
      </dt>
      <dd>
        <%= @loan.periods_in_year %>
      </dd>

    </dl>
  </div>
</div>

<div>
  <%= line_chart [{name: "Balance", data: @pmt_schedule_chart} , {name: "Adj Balance", data: @adj_pmt_schedule_chart}] %>
  
  <!-- Testing other charting fucntion
  <%#= timeline [
  ["Washington", "1789-04-29", "1797-03-03"],
  ["Adams", "1797-03-03", "1801-03-03"],
  ["Jefferson", "1801-03-03", "1809-03-03"]
] %> -->
</div>

<div class="row mb-3">
  <div class="col-md-12">
    <h1>
      Loan Schedule
    </h1>
  </div>
</div>


<hr>

<div class="row mb-3">
  <div class="col-md-12">
    <%= render "loans/schedule_details", pmt_schedule: @pmt_schedule, pmt_schedule_adj: @pmt_schedule_adj %>
  </div>
</div>