config/routes.rb
Rails.application.routes.draw do
  
  root "loans#index"
  resources :adjustments
  devise_for :users
  resources :loans
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/adjustment.rb
# == Schema Information
#
# Table name: adjustments
#
#  id                 :bigint           not null, primary key
#  payment_occurrence :string
#  loan_id            :integer
#  user_id            :integer
#  pmt_adjustment     :float
#  beg_pay_adj        :integer
#  end_pay_adj        :integer
#  adjustment_details :string
#  created_at         :datetime         not null
#  updated_at         :datetime         not null
#
class Adjustment < ApplicationRecord
    belongs_to :loan
    belongs_to :user
    
    validates :pmt_adjustment, :numericality => { :greater_than => 0 }
    validates :pmt_adjustment, :presence => true
    validates :beg_pay_adj, :numericality => { :greater_than => 0 }
    validates :beg_pay_adj, :presence => true
    #validates_presence_of :end_pay_adj, :if => lambda { |o| o.payment_occurrence == "Between" }
    validates :end_pay_adj, :presence => true, :if => :payment_occurrence_between

  def payment_occurrence_between
    payment_occurrence == 'Between'
  end
    
end

app/controllers/adjustments_controller.rb
class AdjustmentsController < ApplicationController
  before_action :set_adjustment, only: %i[ show edit update destroy ]
  after_action :verify_policy_scoped, only: [:index]
  after_action :verify_authorized, except: [:index]

  # GET /adjustments or /adjustments.json
  def index
    #@adjustments = current_user.adjustments.all
    @adjustments = policy_scope(Adjustment)
  end

  # GET /adjustments/1 or /adjustments/1.json
  def show
    authorize @adjustment
  end

  # GET /adjustments/new
  def new
    @adjustment = Adjustment.new
    authorize @adjustment
  end

  # GET /adjustments/1/edit
  def edit
    authorize @adjustment
  end

  # POST /adjustments or /adjustments.json
  def create
    @adjustment = Adjustment.new(adjustment_params)
    authorize @adjustment

    respond_to do |format|
      if @adjustment.save
        format.html { redirect_to adjustments_path, notice: "Adjustment was successfully created." }
        format.json { render :show, status: :created, location: @adjustment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @adjustment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adjustments/1 or /adjustments/1.json
  def update
    authorize @adjustment
    respond_to do |format|
      if @adjustment.update(adjustment_params)
        format.html { redirect_to adjustments_path, notice: "Adjustment was successfully updated." }
        format.json { render :show, status: :ok, location: @adjustment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @adjustment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adjustments/1 or /adjustments/1.json
  def destroy
    authorize @adjustment
    @adjustment.destroy
    respond_to do |format|
      format.html { redirect_to adjustments_url, notice: "Adjustment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adjustment
      @adjustment = Adjustment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def adjustment_params
      params.require(:adjustment).permit(:payment_occurrence, :loan_id, :user_id, :pmt_adjustment, :beg_pay_adj, :end_pay_adj, :adjustment_details)
    end
end

app/helpers/adjustments_helper.rb
module AdjustmentsHelper
end

app/views/adjustments/_form.html.erb
<%= form_with(model: adjustment) do |form| %>
  <% if adjustment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(adjustment.errors.count, "error") %> prohibited this adjustment from being saved:</h2>

      <ul>
        <% adjustment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

<hr>
  <div  class="form-group">
    <%= form.label :payment_occurrence %>
    <%= form.select :payment_occurrence, [['Recurring'], ['One Time'], ['Between']] , {prompt: "Select occurrence type"}, {class: "form-control" } %>

  </div>

  <div class="form-group">
    <%= form.label :loan_id, "Which loan does this apply to?" %>
    <%= form.collection_select :loan_id, current_user.loans.order(:loan_name),:id,:loan_name, {include_blank: true},  {class: "form-control"} %>  
  </div>

  <%= form.hidden_field :user_id, value: current_user.id%>

  <div class="form-group">
    <%= form.label :pmt_adjustment, "What is the value in dollars of the adjustment?" %>
    <%= form.text_field :pmt_adjustment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :beg_pay_adj, "In what period does this pay adjustment begin?" %>
    <%= form.number_field :beg_pay_adj, class: "form-control" %>
  </div>

  <div id="end_adjustment" class="form-group">
    <%= form.label :end_pay_adj, "In what period does this pay adjustment end?" %>
    <%= form.number_field :end_pay_adj, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :adjustment_details, "Give a name to this adjustment" %>
    <%= form.text_field :adjustment_details, class: "form-control" %>
  </div>

  <div class="btn btn-block btn-outline-primary">
    <%= form.submit %>
  </div>
<% end %>
<hr>

app/views/adjustments/_index_row.html.erb
      <tr>
        <td><%= adjustment.payment_occurrence %></td>
        <td><%= adjustment.loan.loan_name %></td>
        <td><%= number_to_currency(adjustment.pmt_adjustment) %></td>
        <td><%= adjustment.beg_pay_adj %></td>
        <td>
          <% if adjustment.payment_occurrence == "Between" %>
            <%= adjustment.end_pay_adj %></td>
          <% else %>
            -
          <% end %>
        <td><%= adjustment.adjustment_details %></td>
        <td><%= link_to 'Edit', edit_adjustment_path(adjustment) %></td>
        <td><%= link_to 'Delete', adjustment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

app/views/adjustments/edit.html.erb
<h1>Editing Adjustment</h1>

<%= render 'form', adjustment: @adjustment %>

<%= link_to 'Show', @adjustment %> |
<%= link_to 'Back', adjustments_path %>

app/views/adjustments/index.html.erb
<h1>Adjustments</h1>

<%= link_to 'Add a new adjustment',new_adjustment_path, class: "btn btn-block btn-outline-secondary" %>

<div class="row mb-3">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Payment Occurrence </th>
          <th> Loan </th>
          <th> Adjustment </th>
          <th> Beginning Adjustment Period </th>
          <th> Ending Adjustment Period </th>
          <th> Adjustment details </th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @adjustments.each do |adjustment| %>
          <%= render "adjustments/index_row", adjustment: adjustment %>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

<br>

app/views/adjustments/new.html.erb
<h1>New Adjustment</h1>

<%= render 'form', adjustment: @adjustment %>

<%= link_to 'Back', adjustments_path %>

app/views/adjustments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment occurrence:</strong>
  <%= @adjustment.payment_occurrence %>
</p>

<p>
  <strong>Loan:</strong>
  <%= @adjustment.loan_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @adjustment.user_id %>
</p>

<p>
  <strong>Pmt adjustment:</strong>
  <%= @adjustment.pmt_adjustment %>
</p>

<p>
  <strong>Beg pay adj:</strong>
  <%= @adjustment.beg_pay_adj %>
</p>

<p>
  <strong>End pay adj:</strong>
  <%= @adjustment.end_pay_adj %>
</p>

<p>
  <strong>Adjustment details:</strong>
  <%= @adjustment.adjustment_details %>
</p>

<%= link_to 'Edit', edit_adjustment_path(@adjustment) %> |
<%= link_to 'Back', adjustments_path %>